String teacherName("Abbas Nabi"); //Skriv den rette datatype og et passende variabelnavn foran denne værdi: String teacherName= "Abbas Nabi"
int daysInAYear = 365;
String city = "København";
boolean stateMent = true;
char numbers = 60*24;
float deciMal = 22.12
String nameLine = "Hej, jeg heddder "+teachername;
boolean stateMent = false;
float number = 2.2 + 33;
char letters = 'S';
